### ISSUE TITLE
Support for typedef

### ISSUE THREAD

**Issue by chrisgervang** [thundernet8/thrift2ts#1]
Thrift has a notion of type aliases called typedef, and I was wondering if this library could include support for that.

This could be done with the `type` feature of typescript.

For example, this could generate:
```
typedef string UUID
export type UUID = string;
```
```
typedef string Timestamp
export type Timestamp = string;
```

**Comment by thundernet8** [comment]
Thanks, PR has been merged and a new version of npm package also has been published

**Comment by chrisgervang** [comment]
Thanks!! I may have another PR coming to type `i32`'s differently. My thrift stuff is parsing `i32` as a `Buffer` type, since JS doesn't have an integer type. I'll make an issue if that is something I can't change in my thrift client library.
